name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Subir a API
      run: npm start &

    - name: Esperar a porta 3000 responder
      run: |
        for i in {1..30}; do
          nc -z localhost 3000 && echo "API está pronta!" && exit 0
          echo "Aguardando a API subir..."
          sleep 1
        done
        echo "A API não subiu a tempo" && exit 1

    - name: Rodar os testes de controller
      run: npm run test-controller

    - name: Rodar os testes de API via HTTP
      run: npm run test-external

      
